package io.github.stack07142.trendingingithub.model;

import java.util.ArrayList;
import java.util.List;

public class FilterData {

    List<String> languageList = new ArrayList<>();
    List<String> createdList = new ArrayList<>();

    public FilterData() {

        languageList.add("All");

        languageList.add("Python");
        languageList.add("Java");
        languageList.add("C++");
        languageList.add("C#");
        languageList.add("C");
        languageList.add("JavaScript");
        languageList.add("Ruby");
        languageList.add("PHP");
        languageList.add("Haskell");
        languageList.add("Go");
        languageList.add("Scala");
        languageList.add("Swift");
        languageList.add("Kotlin");
        languageList.add("Perl");
        languageList.add("Objective-C");
        languageList.add("R");
        languageList.add("Visual Basic");
        languageList.add("Lua");
        languageList.add("Clojure");
        languageList.add("TypeScript");
        languageList.add("Rust");
        languageList.add("Tcl");
        languageList.add("CoffeeScript");
        languageList.add("Elixir");
        languageList.add("Julia");
        languageList.add("Crystal");
        languageList.add("PowerShell");
        languageList.add("Groovy");
        languageList.add("CSS");
        languageList.add("Shell");
        languageList.add("Matlab");

        languageList.add("1C Enterprise");
        languageList.add("ABAP");
        languageList.add("AGS Script");
        languageList.add("AMPL");
        languageList.add("ANTLR");
        languageList.add("API Blueprint");
        languageList.add("APL");
        languageList.add("ASP");
        languageList.add("ATS");
        languageList.add("ActionScript");
        languageList.add("Ada");
        languageList.add("Agda");
        languageList.add("Alloy");
        languageList.add("Alpine Abuild");
        languageList.add("Apex");
        languageList.add("Apollo Guidance Computer");
        languageList.add("AppleScript");
        languageList.add("Arc");
        languageList.add("Arduino");
        languageList.add("AspectJ");
        languageList.add("Augeas");
        languageList.add("AutoHotkey");
        languageList.add("AutoIt");
        languageList.add("Awk");
        languageList.add("Batchfile");
        languageList.add("Befunge");
        languageList.add("Bison");
        languageList.add("BitBake");
        languageList.add("BlitzBasic");
        languageList.add("BlitzMax");
        languageList.add("Bluespec");
        languageList.add("Boo");
        languageList.add("Brainfuck");
        languageList.add("Brightscript");
        languageList.add("Bro");
        languageList.add("C2hs Haskell");
        languageList.add("CLIPS");
        languageList.add("CMake");
        languageList.add("COBOL");
        languageList.add("CWeb");
        languageList.add("Cap'n Proto");
        languageList.add("CartoCSS");
        languageList.add("Ceylon");
        languageList.add("Chapel");
        languageList.add("Charity");
        languageList.add("ChucK");
        languageList.add("Cirru");
        languageList.add("Clarion");
        languageList.add("Clean");
        languageList.add("Click");
        languageList.add("ColdFusion");
        languageList.add("ColdFusion CFC");
        languageList.add("Common Lisp");
        languageList.add("Component Pascal");
        languageList.add("Cool");
        languageList.add("Coq");
        languageList.add("Csound");
        languageList.add("Csound Document");
        languageList.add("Csound Score");
        languageList.add("Cuda");
        languageList.add("Cycript");
        languageList.add("Cython");
        languageList.add("D");
        languageList.add("DIGITAL Command Language");
        languageList.add("DM");
        languageList.add("DTrace");
        languageList.add("Dart");
        languageList.add("Dogescript");
        languageList.add("Dylan");
        languageList.add("E");
        languageList.add("ECL");
        languageList.add("ECLiPSe");
        languageList.add("EQ");
        languageList.add("Eagle");
        languageList.add("Eiffel");
        languageList.add("Elm");
        languageList.add("Emacs Lisp");
        languageList.add("EmberScript");
        languageList.add("Erlang");
        languageList.add("F#");
        languageList.add("FLUX");
        languageList.add("Factor");
        languageList.add("Fancy");
        languageList.add("Fantom");
        languageList.add("Filebench WML");
        languageList.add("Filterscript");
        languageList.add("Forth");
        languageList.add("Fortran");
        languageList.add("FreeMarker");
        languageList.add("Frege");
        languageList.add("GAMS");
        languageList.add("GAP");
        languageList.add("GCC Machine Description");
        languageList.add("GDB");
        languageList.add("GDScript");
        languageList.add("GLSL");
        languageList.add("Game Maker Language");
        languageList.add("Genie");
        languageList.add("Genshi");
        languageList.add("Gentoo Ebuild");
        languageList.add("Gentoo Eclass");
        languageList.add("Gherkin");
        languageList.add("Glyph");
        languageList.add("Gnuplot");
        languageList.add("Golo");
        languageList.add("Gosu");
        languageList.add("Grace");
        languageList.add("Grammatical Framework");
        languageList.add("Groovy");
        languageList.add("Groovy Server Pages");
        languageList.add("HCL");
        languageList.add("HLSL");
        languageList.add("HTML");
        languageList.add("Hack");
        languageList.add("Harbour");
        languageList.add("Haxe");
        languageList.add("Hy");
        languageList.add("HyPhy");
        languageList.add("IDL");
        languageList.add("IGOR Pro");
        languageList.add("Idris");
        languageList.add("Inform 7");
        languageList.add("Inno Setup");
        languageList.add("Io");
        languageList.add("Ioke");
        languageList.add("Isabelle");
        languageList.add("Isabelle ROOT");
        languageList.add("J");
        languageList.add("JFlex");
        languageList.add("JSONiq");
        languageList.add("JSX");
        languageList.add("Jasmin");
        languageList.add("Java Server Pages");
        languageList.add("Jison");
        languageList.add("Jison Lex");
        languageList.add("Jolie");
        languageList.add("Jupyter Notebook");
        languageList.add("KRL");
        languageList.add("KiCad");
        languageList.add("LFE");
        languageList.add("LLVM");
        languageList.add("LOLCODE");
        languageList.add("LSL");
        languageList.add("LabVIEW");
        languageList.add("Lasso");
        languageList.add("Lean");
        languageList.add("Lex");
        languageList.add("LilyPond");
        languageList.add("Limbo");
        languageList.add("Literate Agda");
        languageList.add("Literate CoffeeScript");
        languageList.add("Literate Haskell");
        languageList.add("LiveScript");
        languageList.add("Logos");
        languageList.add("Logtalk");
        languageList.add("LookML");
        languageList.add("LoomScript");
        languageList.add("M");
        languageList.add("M4");
        languageList.add("M4Sugar");
        languageList.add("MAXScript");
        languageList.add("MQL4");
        languageList.add("MQL5");
        languageList.add("MTML");
        languageList.add("MUF");
        languageList.add("Makefile");
        languageList.add("Mako");
        languageList.add("Mask");
        languageList.add("Mathematica");
        languageList.add("Max");
        languageList.add("Mercury");
        languageList.add("Meson");
        languageList.add("Metal");
        languageList.add("MiniD");
        languageList.add("Mirah");
        languageList.add("Modelica");
        languageList.add("Modula-2");
        languageList.add("Module Management System");
        languageList.add("Monkey");
        languageList.add("Moocode");
        languageList.add("MoonScript");
        languageList.add("Myghty");
        languageList.add("NCL");
        languageList.add("NSIS");
        languageList.add("Nemerle");
        languageList.add("NetLinx");
        languageList.add("NetLinx+ERB");
        languageList.add("NetLogo");
        languageList.add("NewLisp");
        languageList.add("Nginx");
        languageList.add("Nim");
        languageList.add("Nit");
        languageList.add("Nix");
        languageList.add("Nu");
        languageList.add("NumPy");
        languageList.add("OCaml");
        languageList.add("Objective-C++");
        languageList.add("Objective-J");
        languageList.add("Omgrofl");
        languageList.add("Opa");
        languageList.add("Opal");
        languageList.add("OpenCL");
        languageList.add("OpenEdge ABL");
        languageList.add("OpenRC runscript");
        languageList.add("OpenSCAD");
        languageList.add("Ox");
        languageList.add("Oxygene");
        languageList.add("Oz");
        languageList.add("P4");
        languageList.add("PAWN");
        languageList.add("PLSQL");
        languageList.add("PLpgSQL");
        languageList.add("POV-Ray SDL");
        languageList.add("Pan");
        languageList.add("Papyrus");
        languageList.add("Parrot");
        languageList.add("Parrot Assembly");
        languageList.add("Parrot Internal Representation");
        languageList.add("Pascal");
        languageList.add("Pep8");
        languageList.add("Perl6");
        languageList.add("PicoLisp");
        languageList.add("PigLatin");
        languageList.add("Pike");
        languageList.add("PogoScript");
        languageList.add("Pony");
        languageList.add("PostScript");
        languageList.add("PowerBuilder");
        languageList.add("Processing");
        languageList.add("Prolog");
        languageList.add("Propeller Spin");
        languageList.add("Puppet");
        languageList.add("Pure Data");
        languageList.add("PureBasic");
        languageList.add("PureScript");
        languageList.add("Python console");
        languageList.add("QML");
        languageList.add("QMake");
        languageList.add("RAML");
        languageList.add("REALbasic");
        languageList.add("REXX");
        languageList.add("RUNOFF");
        languageList.add("Racket");
        languageList.add("Ragel");
        languageList.add("Rascal");
        languageList.add("Reason");
        languageList.add("Rebol");
        languageList.add("Red");
        languageList.add("Redcode");
        languageList.add("Ren'Py");
        languageList.add("RenderScript");
        languageList.add("RobotFramework");
        languageList.add("Roff");
        languageList.add("Rouge");
        languageList.add("SAS");
        languageList.add("SMT");
        languageList.add("SQF");
        languageList.add("SQLPL");
        languageList.add("SRecode Template");
        languageList.add("Sage");
        languageList.add("SaltStack");
        languageList.add("Scheme");
        languageList.add("Scilab");
        languageList.add("Self");
        languageList.add("ShaderLab");
        languageList.add("ShellSession");
        languageList.add("Shen");
        languageList.add("Slash");
        languageList.add("Smali");
        languageList.add("Smalltalk");
        languageList.add("Smarty");
        languageList.add("SourcePawn");
        languageList.add("Squirrel");
        languageList.add("Stan");
        languageList.add("Standard ML");
        languageList.add("Stata");
        languageList.add("SuperCollider");
        languageList.add("SystemVerilog");
        languageList.add("TI Program");
        languageList.add("TLA");
        languageList.add("TXL");
        languageList.add("Tcsh");
        languageList.add("TeX");
        languageList.add("Terra");
        languageList.add("Thrift");
        languageList.add("Turing");
        languageList.add("Unified Parallel C");
        languageList.add("Unix Assembly");
        languageList.add("Uno");
        languageList.add("UnrealScript");
        languageList.add("UrWeb");
        languageList.add("VCL");
        languageList.add("VHDL");
        languageList.add("Vala");
        languageList.add("Verilog");
        languageList.add("Vim script");
        languageList.add("Volt");
        languageList.add("Vue");
        languageList.add("Web Ontology Language");
        languageList.add("WebAssembly");
        languageList.add("WebIDL");
        languageList.add("X10");
        languageList.add("XC");
        languageList.add("XPages");
        languageList.add("XProc");
        languageList.add("XQuery");
        languageList.add("XS");
        languageList.add("XSLT");
        languageList.add("Xojo");
        languageList.add("Xtend");
        languageList.add("Yacc");
        languageList.add("Zephir");
        languageList.add("Zimpl");
        languageList.add("eC");
        languageList.add("fish");
        languageList.add("mupad");
        languageList.add("nesC");
        languageList.add("ooc");
        languageList.add("wisp");
        languageList.add("xBase");

        createdList.add("today");
        createdList.add("this week");
        createdList.add("this month");
        createdList.add("this year");
    }

    public List<String> getLanguageList() {
        return languageList;
    }

    public void setLanguageList(List<String> languageList) {
        this.languageList = languageList;
    }

    public List<String> getCreatedList() {
        return createdList;
    }

    public void setCreatedList(List<String> createdList) {
        this.createdList = createdList;
    }
}
