package io.github.stack07142.trendingingithub.model;

import android.graphics.Color;

import java.util.HashMap;

public class LanguageColorsData {

    private final HashMap<String, String> colorMap;

    public LanguageColorsData() {

        colorMap = new HashMap<>();

        setColors();
    }

    private void setColors() {

        colorMap.put("REALbasic", "null");
        colorMap.put("Lasso", "#999999");
        colorMap.put("ShaderLab", "null");
        colorMap.put("Ox", "null");
        colorMap.put("Volt", "#1F1F1F");
        colorMap.put("LFE", "null");
        colorMap.put("Oz", "#fab738");
        colorMap.put("Erlang", "#B83998");
        colorMap.put("Pony", "null");
        colorMap.put("PureBasic", "#5a6986");
        colorMap.put("1C Enterprise", "#814CCC");
        colorMap.put("ABAP", "#E8274B");
        colorMap.put("API Blueprint", "#2ACCA8");
        colorMap.put("Cirru", "#ccccff");
        colorMap.put("CWeb", "null");
        colorMap.put("Oxygene", "#cdd0e3");
        colorMap.put("LLVM", "#185619");
        colorMap.put("nesC", "#94B0C7");
        colorMap.put("Redcode", "null");
        colorMap.put("Verilog", "#b2b7f8");
        colorMap.put("Bison", "null");
        colorMap.put("OpenSCAD", "null");
        colorMap.put("Gnuplot", "#f0a9f0");
        colorMap.put("Pascal", "#E3F171");
        colorMap.put("CartoCSS", "null");
        colorMap.put("Eagle", "#814C05");
        colorMap.put("Clojure", "#db5855");
        colorMap.put("MAXScript", "#00a6a6");
        colorMap.put("PowerShell", "#012456");
        colorMap.put("Smali", "null");
        colorMap.put("Smarty", "null");
        colorMap.put("GAMS", "null");
        colorMap.put("Rouge", "#cc0088");
        colorMap.put("NetLinx", "#0aa0ff");
        colorMap.put("Rust", "#dea584");
        colorMap.put("Jison Lex", "null");
        colorMap.put("Objective-C++", "#6866fb");
        colorMap.put("PLpgSQL", "null");
        colorMap.put("MQL4", "#62A8D6");
        colorMap.put("RAML", "#77d9fb");
        colorMap.put("MQL5", "#4A76B8");
        colorMap.put("Modelica", "null");
        colorMap.put("JSX", "null");
        colorMap.put("Ragel", "#9d5200");
        colorMap.put("Rascal", "#fffaa0");
        colorMap.put("Idris", "null");
        colorMap.put("SuperCollider", "#46390b");
        colorMap.put("Arc", "#aa2afe");
        colorMap.put("ANTLR", "#9DC3FF");
        colorMap.put("Mako", "null");
        colorMap.put("Squirrel", "#800000");
        colorMap.put("Charity", "null");
        colorMap.put("Elixir", "#6e4a7e");
        colorMap.put("Rebol", "#358a5b");
        colorMap.put("C#", "#178600");
        colorMap.put("C", "#555555");
        colorMap.put("D", "#ba595e");
        colorMap.put("E", "#ccce35");
        colorMap.put("Isabelle ROOT", "null");
        colorMap.put("Monkey", "null");
        colorMap.put("Stan", "#b2011d");
        colorMap.put("TXL", "null");
        colorMap.put("J", "#9EEDFF");
        colorMap.put("M", "null");
        colorMap.put("Groovy Server Pages", "null");
        colorMap.put("BlitzBasic", "null");
        colorMap.put("R", "#198CE7");
        colorMap.put("Cap'n Proto", "null");
        colorMap.put("Genie", "#fb855d");
        colorMap.put("REXX", "null");
        colorMap.put("Game Maker Language", "#8fb200");
        colorMap.put("ASP", "#6a40fd");
        colorMap.put("Zimpl", "null");
        colorMap.put("Java", "#b07219");
        colorMap.put("COBOL", "null");
        colorMap.put("Augeas", "null");
        colorMap.put("Logos", "null");
        colorMap.put("Module Management System", "null");
        colorMap.put("Red", "#f50000");
        colorMap.put("Csound", "null");
        colorMap.put("SystemVerilog", "#DAE1C2");
        colorMap.put("Logtalk", "null");
        colorMap.put("Isabelle", "#FEFE00");
        colorMap.put("X10", "#4B6BEF");
        colorMap.put("fish", "null");
        colorMap.put("HLSL", "null");
        colorMap.put("Pan", "#cc0000");
        colorMap.put("ActionScript", "#882B0F");
        colorMap.put("eC", "#913960");
        colorMap.put("Ada", "#02f88c");
        colorMap.put("ATS", "#1ac620");
        colorMap.put("Opa", "null");
        colorMap.put("ooc", "#b0b77e");
        colorMap.put("Scheme", "#1e4aec");
        colorMap.put("Elm", "#60B5CC");
        colorMap.put("Common Lisp", "#3fb68b");
        colorMap.put("DM", "#447265");
        colorMap.put("Click", "#E4E6F3");
        colorMap.put("Metal", "#8f14e9");
        colorMap.put("NumPy", "null");
        colorMap.put("IDL", "#a3522f");
        colorMap.put("VHDL", "#adb2cb");
        colorMap.put("Racket", "#22228f");
        colorMap.put("Parrot Assembly", "null");
        colorMap.put("RobotFramework", "null");
        colorMap.put("wisp", "#7582D1");
        colorMap.put("Brightscript", "null");
        colorMap.put("Csound Score", "null");
        colorMap.put("F#", "#b845fc");
        colorMap.put("LilyPond", "null");
        colorMap.put("SQLPL", "null");
        colorMap.put("LookML", "#652B81");
        colorMap.put("Thrift", "null");
        colorMap.put("Fancy", "#7b9db4");
        colorMap.put("Alpine Abuild", "null");
        colorMap.put("PureScript", "#1D222D");
        colorMap.put("OpenRC runscript", "null");
        colorMap.put("Golo", "#88562A");
        colorMap.put("Stata", "null");
        colorMap.put("EQ", "#a78649");
        colorMap.put("PAWN", "#dbb284");
        colorMap.put("Moocode", "null");
        colorMap.put("Cuda", "#3A4E3A");
        colorMap.put("Propeller Spin", "#7fa2a7");
        colorMap.put("HCL", "null");
        colorMap.put("EmberScript", "#FFF4F3");
        colorMap.put("OpenEdge ABL", "null");
        colorMap.put("Mirah", "#c7a938");
        colorMap.put("Batchfile", "#C1F12E");
        colorMap.put("Xojo", "null");
        colorMap.put("Meson", "#007800");
        colorMap.put("GAP", "null");
        colorMap.put("Pep8", "#C76F5B");
        colorMap.put("PLSQL", "#dad8d8");
        colorMap.put("Gentoo Eclass", "null");
        colorMap.put("Arduino", "#bd79d1");
        colorMap.put("HyPhy", "null");
        colorMap.put("Crystal", "#776791");
        colorMap.put("Matlab", "#bb92ac");
        colorMap.put("Filterscript", "null");
        colorMap.put("MiniD", "null");
        colorMap.put("DIGITAL Command Language", "null");
        colorMap.put("Makefile", "#427819");
        colorMap.put("Grammatical Framework", "#79aa7a");
        colorMap.put("AutoIt", "#1C3552");
        colorMap.put("TLA", "null");
        colorMap.put("AGS Script", "#B9D9FF");
        colorMap.put("Myghty", "null");
        colorMap.put("Processing", "#0096D8");
        colorMap.put("CLIPS", "null");
        colorMap.put("Shell", "#89e051");
        colorMap.put("Forth", "#341708");
        colorMap.put("Smalltalk", "#596706");
        colorMap.put("Visual Basic", "#945db7");
        colorMap.put("Awk", "null");
        colorMap.put("JavaScript", "#f1e05a");
        colorMap.put("Uno", "null");
        colorMap.put("Mathematica", "null");
        colorMap.put("PigLatin", "#fcd7de");
        colorMap.put("Limbo", "null");
        colorMap.put("POV-Ray SDL", "null");
        colorMap.put("Literate CoffeeScript", "null");
        colorMap.put("C++", "#f34b7d");
        colorMap.put("GCC Machine Description", "null");
        colorMap.put("ECLiPSe", "null");
        colorMap.put("Csound Document", "null");
        colorMap.put("XC", "#99DA07");
        colorMap.put("Cycript", "null");
        colorMap.put("Alloy", "#64C800");
        colorMap.put("JSONiq", "#40d47e");
        colorMap.put("WebIDL", "null");
        colorMap.put("CoffeeScript", "#244776");
        colorMap.put("Python console", "null");
        colorMap.put("XPages", "null");
        colorMap.put("XS", "null");
        colorMap.put("Mercury", "#ff2b2b");
        colorMap.put("C2hs Haskell", "null");
        colorMap.put("LabVIEW", "null");
        colorMap.put("Filebench WML", "null");
        colorMap.put("SRecode Template", "#348a34");
        colorMap.put("Nginx", "#9469E9");
        colorMap.put("Ioke", "#078193");
        colorMap.put("Tcsh", "null");
        colorMap.put("GDB", "null");
        colorMap.put("CMake", "null");
        colorMap.put("Jasmin", "null");
        colorMap.put("Go", "#375eab");
        colorMap.put("NewLisp", "#87AED7");
        colorMap.put("OCaml", "#3be133");
        colorMap.put("Pike", "#005390");
        colorMap.put("Glyph", "#e4cc98");
        colorMap.put("Harbour", "#0e60e3");
        colorMap.put("Literate Haskell", "null");
        colorMap.put("NetLinx+ERB", "#747faa");
        colorMap.put("Haskell", "#29b544");
        colorMap.put("IGOR Pro", "null");
        colorMap.put("Web Ontology Language", "#9cc9dd");
        colorMap.put("Chapel", "#8dc63f");
        colorMap.put("Mask", "#f97732");
        colorMap.put("Perl", "#0298c3");
        colorMap.put("M4Sugar", "null");
        colorMap.put("UnrealScript", "#a54c4d");
        colorMap.put("XProc", "null");
        colorMap.put("Component Pascal", "#B0CE4E");
        colorMap.put("Hy", "#7790B2");
        colorMap.put("Xtend", "null");
        colorMap.put("Dylan", "#6c616e");
        colorMap.put("RenderScript", "null");
        colorMap.put("TI Program", "#A0AA87");
        colorMap.put("AMPL", "#E6EFBB");
        colorMap.put("NCL", "#28431f");
        colorMap.put("ChucK", "null");
        colorMap.put("KiCad", "null");
        colorMap.put("Swift", "#ffac45");
        colorMap.put("SMT", "null");
        colorMap.put("LiveScript", "#499886");
        colorMap.put("VCL", "null");
        colorMap.put("Terra", "#00004c");
        colorMap.put("Objective-J", "#ff0c5a");
        colorMap.put("Jolie", "#843179");
        colorMap.put("Max", "#c4a79c");
        colorMap.put("Io", "#a9188d");
        colorMap.put("QMake", "null");
        colorMap.put("WebAssembly", "#04133b");
        colorMap.put("Cool", "null");
        colorMap.put("Java Server Pages", "null");
        colorMap.put("Unix Assembly", "null");
        colorMap.put("Gosu", "#82937f");
        colorMap.put("Self", "#0579aa");
        colorMap.put("Jupyter Notebook", "#DA5B0B");
        colorMap.put("AutoHotkey", "#6594b9");
        colorMap.put("Dogescript", "#cca760");
        colorMap.put("Clarion", "#db901e");
        colorMap.put("JFlex", "null");
        colorMap.put("Objective-C", "#438eff");
        colorMap.put("PHP", "#4F5D95");
        colorMap.put("Agda", "#315665");
        colorMap.put("Apex", "null");
        colorMap.put("Hack", "#878787");
        colorMap.put("Coq", "null");
        colorMap.put("Vue", "#2c3e50");
        colorMap.put("Prolog", "#74283c");
        colorMap.put("BitBake", "null");
        colorMap.put("ECL", "#8a1267");
        colorMap.put("Genshi", "null");
        colorMap.put("Kotlin", "#F18E33");
        colorMap.put("Julia", "#a270ba");
        colorMap.put("OpenCL", "null");
        colorMap.put("Puppet", "#302B6D");
        colorMap.put("Omgrofl", "#cabbff");
        colorMap.put("Parrot Internal Representation", "null");
        colorMap.put("Fantom", "#dbded5");
        colorMap.put("LoomScript", "null");
        colorMap.put("PicoLisp", "null");
        colorMap.put("Grace", "null");
        colorMap.put("XQuery", "#5232e7");
        colorMap.put("M4", "null");
        colorMap.put("ShellSession", "null");
        colorMap.put("HTML", "#e34c26");
        colorMap.put("NSIS", "null");
        colorMap.put("Apollo Guidance Computer", "null");
        colorMap.put("Groovy", "#e69f56");
        colorMap.put("Fortran", "#4d41b1");
        colorMap.put("Perl6", "#0000fb");
        colorMap.put("Befunge", "null");
        colorMap.put("Factor", "#636746");
        colorMap.put("Jison", "null");
        colorMap.put("Frege", "#00cafe");
        colorMap.put("Slash", "#007eff");
        colorMap.put("Ren'Py", "#ff7f7f");
        colorMap.put("Assembly", "#6E4C13");
        colorMap.put("Eiffel", "#946d57");
        colorMap.put("MUF", "null");
        colorMap.put("Python", "#3572A5");
        colorMap.put("Yacc", "#4B6C4B");
        colorMap.put("Lean", "null");
        colorMap.put("MTML", "#b7e1f4");
        colorMap.put("Boo", "#d4bec1");
        colorMap.put("LSL", "#3d9970");
        colorMap.put("PogoScript", "#d80074");
        colorMap.put("Parrot", "#f3ca0a");
        colorMap.put("Ceylon", "null");
        colorMap.put("Vala", "#fbe5cd");
        colorMap.put("SQF", "#3F3F3F");
        colorMap.put("Gentoo Ebuild", "null");
        colorMap.put("Turing", "#cf142b");
        colorMap.put("Papyrus", "#6600cc");
        colorMap.put("Bluespec", "null");
        colorMap.put("QML", "#44a51c");
        colorMap.put("Scilab", "null");
        colorMap.put("Gherkin", "#5B2063");
        colorMap.put("UrWeb", "null");
        colorMap.put("RUNOFF", "#665a4e");
        colorMap.put("Zephir", "#118f9e");
        colorMap.put("Tcl", "#e4cc98");
        colorMap.put("Dart", "#00B4AB");
        colorMap.put("DTrace", "null");
        colorMap.put("Literate Agda", "null");
        colorMap.put("ColdFusion", "#ed2cd6");
        colorMap.put("KRL", "#28431f");
        colorMap.put("SAS", "#B34936");
        colorMap.put("Standard ML", "#dc566d");
        colorMap.put("FLUX", "#88ccff");
        colorMap.put("Inno Setup", "null");
        colorMap.put("Opal", "#f7ede0");
        colorMap.put("Clean", "#3F85AF");
        colorMap.put("FreeMarker", "#0050b2");
        colorMap.put("NetLogo", "#ff6375");
        colorMap.put("Reason", "null");
        colorMap.put("PostScript", "#da291c");
        colorMap.put("TypeScript", "#2b7489");
        colorMap.put("MoonScript", "null");
        colorMap.put("ColdFusion CFC", "null");
        colorMap.put("xBase", "#403a40");
        colorMap.put("Lua", "#000080");
        colorMap.put("Unified Parallel C", "null");
        colorMap.put("Cython", "null");
        colorMap.put("mupad", "null");
        colorMap.put("Pure Data", "#91de79");
        colorMap.put("Ruby", "#701516");
        colorMap.put("AspectJ", "#a957b0");
        colorMap.put("Brainfuck", "#2F2530");
        colorMap.put("Emacs Lisp", "#c065db");
        colorMap.put("GLSL", "null");
        colorMap.put("LOLCODE", "#cc9900");
        colorMap.put("CSS", "#563d7c");
        colorMap.put("Inform 7", "null");
        colorMap.put("Haxe", "#df7900");
        colorMap.put("P4", "#7055b5");
        colorMap.put("PowerBuilder", "#8f0f8d");
        colorMap.put("Scala", "#c22d40");
        colorMap.put("TeX", "#3D6117");
        colorMap.put("AppleScript", "#101F1F");
        colorMap.put("Nu", "#c9df40");
        colorMap.put("BlitzMax", "#cd6400");
        colorMap.put("XSLT", "#EB8CEB");
        colorMap.put("Sage", "null");
        colorMap.put("GDScript", "null");
        colorMap.put("SaltStack", "#646464");
        colorMap.put("Nemerle", "#3d3c6e");
        colorMap.put("Nim", "#37775b");
        colorMap.put("SourcePawn", "#5c7611");
        colorMap.put("Nit", "#009917");
        colorMap.put("Shen", "#120F14");
        colorMap.put("Modula-2", "null");
        colorMap.put("Roff", "#ecdebe");
        colorMap.put("Vim script", "#199f4b");
        colorMap.put("Nix", "#7e7eff");
        colorMap.put("APL", "#5A8164");
        colorMap.put("Bro", "null");
        colorMap.put("Lex", "#DBCA00");
    }


    public int getColor(String language) {

        if (colorMap.containsKey(language)) {

            return Color.parseColor(colorMap.get(language));
        }

        return Color.parseColor("#969696");
    }
}
